### ISSUE TITLE
check the about updates

### ISSUE THREAD

**Issue by m4sterbunny** [OpenSecuritySummit/oss2018#101]
https://open-security-summit.org/about/

two ref to year - both should be 2018 now

**Comment by m4sterbunny** [comment]
as per non-refresh on slack

**Comment by fzipi** [comment]
Maybe its your browser, I'm seeing it well.

![screenshot from 2018-03-12 09-17-22](https://user-images.githubusercontent.com/3012076/37283316-4e3d15d8-25d6-11e8-96e7-eeadda9c585e.png)

**Comment by m4sterbunny** [comment]
?! Thanks
