### ISSUE TITLE
Contact page??

### ISSUE THREAD

**Issue by m4sterbunny** [OpenSecuritySummit/oss2018#103]
Do we want a page with the address:

Address from Francois: OSS: 13 West Hill, London, SW18 1RB

and a contact mail??

**Comment by m4sterbunny** [comment]
OR - it could be on footer as per the OWASP site (beside the disclaimer)

**Comment by JemmaDSmith** [comment]
Footer plus FAQ page

**Comment by m4sterbunny** [comment]
info@opensecsummit.org

**Comment by Lisa-devseccon** [comment]
Lisa to create design for footer

**Comment by Lisa-devseccon** [comment]
we have got the contact details in the footer now, no need for a contact page.
