### ISSUE TITLE
Clean up participant individual page to mirror last years

### ISSUE THREAD

**Issue by JemmaDSmith** [OpenSecuritySummit/oss2018#111]
![screen shot 2018-03-15 at 20 05 10](https://user-images.githubusercontent.com/34240078/37488338-3634f2a4-288c-11e8-97d5-3d4660c2cf77.png)
https://owaspsummit.org/Participants/ticket-24h-owasp/Jemma-Davis.html

**Comment by fzipi** [comment]
There is a first version online.
