### ISSUE TITLE
https://open-security-summit.org/outcome returns 404 error

### ISSUE THREAD

**Issue by bkimminich** [OpenSecuritySummit/oss2018#1225]
![image](https://user-images.githubusercontent.com/3531020/41113313-93208ab4-6a81-11e8-88a4-78d50a55bc1d.png)

**Comment by fzipi** [comment]
Thanks for reporting!

**Comment by fzipi** [comment]
@bkimminich We added a link to the outcomes from the main menu, and corrected the link from the home page. The outcomes are still being processing by the technical writers, so we have now mainly draft outcomes yet.
