### ISSUE TITLE
Outcomes single page add Company name beside Organizer of Session

### ISSUE THREAD

**Issue by almeidam** [OpenSecuritySummit/oss2018#1298]
![image](https://user-images.githubusercontent.com/4119205/41200224-d398e07a-6ca0-11e8-9d81-4298150b28b0.png)

**Comment by fzipi** [comment]
Weird. Can't reproduce that. This is what I see:
![screenshot from 2018-06-10 06-30-27](https://user-images.githubusercontent.com/3012076/41200269-d2cc7b44-6c77-11e8-93f7-7fc7d5fbcf1c.png)

**Comment by fzipi** [comment]
Now I understood. It needs to be added, is not a bug, it is a feature!

**Comment by almeidam** [comment]
Thx Felipe sorry not to mention it.
