### ISSUE TITLE
Outcomes single page 

### ISSUE THREAD

**Issue by almeidam** [OpenSecuritySummit/oss2018#1299]
![image](https://user-images.githubusercontent.com/4119205/41200275-dc231458-6ca1-11e8-8ef1-cb677d8fe682.png)

**Comment by DavidCervigni** [comment]
Slideshare site:
https://www.slideshare.net/opensecsummit
youtube channel:
https://www.youtube.com/channel/UCl65yi2W9zHlBF7CI250VWw

**Comment by fzipi** [comment]
I think David covered this already.
