### ISSUE TITLE
juice shop reference- still needed?

### ISSUE THREAD

**Issue by m4sterbunny** [OpenSecuritySummit/oss2018#135]
This faq https://github.com/OpenSecuritySummit/oss2018/edit/master/content/faq/Infrastructure-needs.md

based on old page links to Juice shop... will this be true for this year... do we need a Juice Shop working session page opened?

**Comment by almeidam** [comment]
juiceshop done

**Comment by VasBu** [comment]
@almeidam , is it done or not? B-)

**Comment by almeidam** [comment]
yes
