### ISSUE TITLE
Outcomes organized by tracks to be displayed on the homepage

### ISSUE THREAD

**Issue by VasBu** [OpenSecuritySummit/oss2018#1353]
- [x] The home page would have tracks as a boxes and list outcomes inside respectively. 
- [x] At the bottom of the boxes that represents tracks have to have a link "See all outcomes" which will redirect to https://open-security-summit.org/outcomes/ (move the current link from "Latest Outcomes" section to the "Recent Outcomes" section.
- [x] Remove current section "Latest Outcomes" from the homepage.
- [x] The list only featured outcomes in the boxes which represents the tracks.
- [x] Rename "Recent Outcomes" into "Featured Outcomes".
![image](https://user-images.githubusercontent.com/15072044/41277836-9c83b4b4-6e28-11e8-9ce9-43d38ecbcd77.png)

**Comment by fzipi** [comment]
I think I made all this. Please recheck :)

**Comment by VasBu** [comment]
@fzipi  you are flash! B-)
