### ISSUE TITLE
Add icons for video, presentation, photos

### ISSUE THREAD

**Issue by VasBu** [OpenSecuritySummit/oss2018#1361]
- As an attachment (additional materials) to the outcomes can be: **video**, **presentation** and **photos**
- The outcomes page (http://localhost:1313/outcomes/) which includes list of outcomes have to include additional icons behind outcomes to announce that an outcome include video, presentation or photos.
- The existing solution display only icons for status of an outcome and if the outcome is featured outcome.
- the new icons has to be with a same style as status and featured sessions are.

![image](https://user-images.githubusercontent.com/15072044/41285456-83debefe-6e3c-11e8-9eed-2ddb52dabccf.png)

**Comment by fzipi** [comment]
The support is there already. Maybe there are not many sessions with videos and/or presentations?
![screenshot from 2018-06-12 19-26-50](https://user-images.githubusercontent.com/3012076/41320564-b1e4638c-6e76-11e8-9810-033aa8a67fe6.png)
