### ISSUE TITLE
OWASP references have crept back in after my clearout!

### ISSUE THREAD

**Issue by m4sterbunny** [OpenSecuritySummit/oss2018#138]
There are a few changes needed on this page:

https://github.com/OpenSecuritySummit/oss2018/blob/master/content/faq/remote-participant.md

refs to OWASP 2017 need to go- the image/example is also a little oversized

Plus who was the clever bugger that made a customised hangouts meet- I want to do the same.

**Comment by m4sterbunny** [comment]
There is also an old link to rooms- to direct people to remote access
https://owaspsummit.org/pages/schedule/by-room/Mon.html

**Comment by fzipi** [comment]
That links are generated from the data... when we have more data :)

**Comment by almeidam** [comment]
resolved
