### ISSUE TITLE
links to old template doc

### ISSUE THREAD

**Issue by m4sterbunny** [OpenSecuritySummit/oss2018#152]
This link needs to be updated AND TESTED

https://github.com/OpenSecuritySummit/oss2018/blob/master/content/participant/Template.md (results in 404)

probably needs the _template.md I am going to do the update and amend to shortcode format

BUT
in the alice in wonderland world I am currently running around in I can't test- the site does not update within a few minutes (as per the info in this page), not even within a few hours!

page edited is https://open-security-summit.org/faq/registration-info/

**Comment by fzipi** [comment]
This was solved in d8a2cb0.
