### ISSUE TITLE
participant type

### ISSUE THREAD

**Issue by m4sterbunny** [OpenSecuritySummit/oss2018#153]
I am thinking that the meta for the templates probably needs to be 

type: onsite OR type: remote

currently, we have "participant"
May I adjust the templates and current participants so that you have this switch?

**Comment by fzipi** [comment]
The default is onsite, and when we add a type it should be 'remote' (or another type). But I think we can add to all participants and the template 'onsite'.

**Comment by DinisCruz** [comment]
This is now done via the different locations the participant file can be created
