### ISSUE TITLE
Create page with last year's photos (and info)

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#160]
This is the page that should be used to show the power of last year's Summit

Photo Album:  https://photos.app.goo.gl/emmfMMNW4FMTNg7l1
pics in Summit debrief: https://www.slideshare.net/owaspsummit/owasp-summit-debrief-v10-jun-2017

**Comment by VasBu** [comment]
This requirement is related with #42 . Photo gallery from the summit 2017 can be part of a separate page defined the mentioned issue.
