### ISSUE TITLE
Update logo to include the 'supported by Owasp' tag

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#163]
![image](https://user-images.githubusercontent.com/656739/38361519-9b0ea348-38c5-11e8-95aa-7c8e7f183b4f.png)

**Comment by fzipi** [comment]
![open-security-summit-rgb](https://user-images.githubusercontent.com/3012076/38368825-bae1f700-38bc-11e8-9239-869d87c639ee.png)

**Comment by Lisa-devseccon** [comment]
![open-security-summit---rgb-horizontal-white](https://user-images.githubusercontent.com/27144792/39124031-393dcf70-46fa-11e8-91c7-dd7d2da7fc94.png)
![open-security-summit---rgb-horizontal](https://user-images.githubusercontent.com/27144792/39124032-39794316-46fa-11e8-8bd6-b1e062fd1de5.png)
Like this? For the website I assume?

**Comment by Lisa-devseccon** [comment]
Sorry for making you change this again, but I just saw that the 'supported by owasp' is almost too small to read on the website. Can you use this one instead please:
![open-security-summit---rgb---horizontal](https://user-images.githubusercontent.com/27144792/39195879-0d4914c8-47e1-11e8-8f76-0766d48ba90c.png)

**Comment by DinisCruz** [comment]
I'm doing this now
