### ISSUE TITLE
Improve design of Tracks page

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#165]
Which doesn't look very good at the moment

![image](https://user-images.githubusercontent.com/656739/38361759-5a2a2158-38c6-11e8-8ec0-bf5e02fcdf3e.png)

**Comment by DinisCruz** [comment]
Improved it a bit
![image](https://user-images.githubusercontent.com/656739/38365134-0f081380-38d3-11e8-81cb-aeb2c796ffd7.png)

**Comment by fzipi** [comment]
I think the tracks are covered, and we can close this one.
