### ISSUE TITLE
Improve site description so shows up better on searches and links

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#169]
![image](https://user-images.githubusercontent.com/656739/38366483-c490d8dc-38d7-11e8-8231-f037e1673317.png)

**Comment by fzipi** [comment]
It is showing better now.
![screenshot from 2018-04-17 23-52-06](https://user-images.githubusercontent.com/3012076/38909285-62fd4b6a-429a-11e8-9d3e-ed71199d11b8.png)
