### ISSUE TITLE
Improve participant page layout

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#178]
doesn't look very good at the moment  

![image](https://user-images.githubusercontent.com/656739/38379619-2831a8c8-38f9-11e8-9c79-027ce09a9fb7.png)

**Comment by fzipi** [comment]
I had one in mind, will post a screenshot in a bit.

**Comment by fzipi** [comment]
@DinisCruz What do you think about [this one](http://themes.gohugo.io/theme/hugo-orbit-theme/)?

**Comment by VasBu** [comment]
@fzipi , Do we have some other templates that could be used and which are in line with directions from @DinisCruz ? @fzipi if you can point to some repository with templates (I guess templates for hugo), I can spend some time to identify some of them that could be useful?

If not, we can probably use the layout from the previous summit, here: 
https://owaspsummit.org/Participants/ticket-24h-owasp/Achim-Hoffmann.html

Maybe some improvements that we can do on top of the old layout. If there is a possibility for reusing of the code from the previous website, that will be hitting the target into the center.

What do you think!? @DinisCruz , @fzipi

**Comment by fzipi** [comment]
The hugo themes directory can be found [here](https://themes.gohugo.io).

Let me see if the old code can be reused.

**Comment by VasBu** [comment]
@fzipi , OK. I'll spend some time to browse the themes and to try to find something appropriate, but please check if we can just get the layout/page from the past summit.

**Comment by frontexpert** [comment]
@fzipi Finished participants page implement. Please check files on slack

**Comment by fzipi** [comment]
@frontexpert What you did was the participants list page, not the individual participant, right?
