### ISSUE TITLE
Improve Buy page

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#181]
So that it looks like the previous one https://owaspsummit.org/website/buy-ticket.html

![image](https://user-images.githubusercontent.com/656739/38384367-e077dd5a-3906-11e8-831d-ec4cf43d2b2c.png)

**Comment by fzipi** [comment]
@DinisCruz I've made a simple copy of that one, but I saw that there are different options this year. Should I put the options that are in the eventbrite site only?

**Comment by fzipi** [comment]
This was done in f514adef7441d59c9ac63027aac859ebdfdefeda.
