### ISSUE TITLE
Categories and Tags are not working (and don't make sense on user sessions)

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#193]
not only we need to think better where they are shown, we need to fix the page used to show them, which at the moment looks like this

![image](https://user-images.githubusercontent.com/656739/38467679-f8c3be22-3b33-11e8-9062-399b3d9931e8.png)

Here is what they look in a user session

![image](https://user-images.githubusercontent.com/656739/38467693-1122349e-3b34-11e8-8b55-ce41db87575c.png)

**Comment by fzipi** [comment]
Fiex the categories list display on f61ca92.
