### ISSUE TITLE
Need visual clue to show which track we are in and type of session

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#194]
i.e. it should be easy to see the different types of sessions (working session, user session, keynote) and the track (if any) that that session belongs to

![image](https://user-images.githubusercontent.com/656739/38467717-47439310-3b34-11e8-8d0e-38d1955e3fb6.png)

**Comment by fzipi** [comment]
We can add labels, as the first line of content, for example.

**Comment by fzipi** [comment]
I added some visual clues to show the difference. Do we need to improve those labels?
![screenshot from 2018-04-22 23-50-51](https://user-images.githubusercontent.com/3012076/39104910-faf2a64e-4688-11e8-814d-38d4bc0d7b22.png)
![screenshot from 2018-04-22 23-51-31](https://user-images.githubusercontent.com/3012076/39104927-1110ae62-4689-11e8-99e0-a6f1990c62eb.png)

**Comment by DinisCruz** [comment]
only thing missing is to link the track name to the track

**Comment by fzipi** [comment]
Added in 891fec2.
