### ISSUE TITLE
Search is not working correctly 

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#195]
![image](https://user-images.githubusercontent.com/656739/38467623-7d79577c-3b33-11e8-8ff6-09a867253f37.png)

goes to 

![image](https://user-images.githubusercontent.com/656739/38467628-a06260b2-3b33-11e8-8f74-3f3f0c3494cb.png)

**Comment by fzipi** [comment]
@DinisCruz Search depends on the `baseurl` value from config.

**Comment by DinisCruz** [comment]
would it be worth looking at the Hugo search?

I've seen that work quite well, my only question is how it affects the side speed

**Comment by fzipi** [comment]
It is working, now that we changed the siteurl to the full url.

**Comment by fzipi** [comment]
We in fact took out the search from the site. It is in no template anymore.

@DinisCruz If we need the search back, we need to put it on a template. If not, just close this one.

Right now is on `layouts/blog/single.html`, but we are not using that one.

**Comment by VasBu** [comment]
It looks like that we can close this one. If it's necessary we provide search for the website, we can reopen it.
