### ISSUE TITLE
Question: Participants in Black and While or in colour

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#199]
Which one do you prefer  (A or B)

## Option A (with colour)

![image](https://user-images.githubusercontent.com/656739/38467984-b39c1e26-3b37-11e8-9284-dfa187ed9a64.png)

## Option B (in B&W)

![image](https://user-images.githubusercontent.com/656739/38467981-ac5f05d8-3b37-11e8-9eea-936ab50f7bc5.png)

**Comment by fzipi** [comment]
option B was requested by @JemmaDSmith.
option A is good for me.

**Comment by fzipi** [comment]
Well, if no one has another opinion, I suggest we stay with colour and close this one.
