### ISSUE TITLE
CSS issue issue on colons

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#201]
At the moment it shows like a weird dot

code:

![image](https://user-images.githubusercontent.com/656739/38468291-93f01a4c-3b3b-11e8-9c35-2bfa830fe756.png)

looks like this:

![image](https://user-images.githubusercontent.com/656739/38468278-766122f0-3b3b-11e8-98b7-3e9bae28f86c.png)

**Comment by fzipi** [comment]
This is somehow font related.
I pointed to the google font site, and:
![screenshot from 2018-04-09 22-50-53](https://user-images.githubusercontent.com/3012076/38531862-801f31b6-3c48-11e8-8340-1b247ce469bf.png)

**Comment by fzipi** [comment]
Fixed with the inclusion of new woff files.
