### ISSUE TITLE
Fix Owasp Summit 2017 logo on owaspsummit.org

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#203]
At the moment it is showing the wrong logo: https://owaspsummit.org/

![image](https://user-images.githubusercontent.com/656739/38470234-bc046e86-3b57-11e8-91d5-cbaf5bdf8a02.png)

it should show last years logo (with 2017(

**Comment by fzipi** [comment]
Fixed logo and title (said "OWASP Summit 2018").
