### ISSUE TITLE
Tracks need to be a category

### ISSUE THREAD

**Issue by fzipi** [OpenSecuritySummit/oss2018#204]
It is much more simple to keep tracks as categories.

We should create a category named `track` and use it as a hugo category, which will simplify things.

**Comment by DinisCruz** [comment]
kinda, the problem is that we need to control better what is a track and what is inside it (including from a editing point of view)

We also need to list 'Topics' (or areas) like we did last year, which will help for the tracks that are not big enough to really be tracks 

We can use the Category to map this

**Comment by VasBu** [comment]
@fzipi , would you please tell me if this one is already resolved?
Do we need to do anything additionally about this one?

Is it must we set "categories" property in session page/file?

![image](https://user-images.githubusercontent.com/15072044/39999648-e9c01228-5789-11e8-8092-e69dc163ce2e.png)

**Comment by fzipi** [comment]
Well, now it doesn't make much sense now, unless we want to rewrite lots of things.

Hugo has a well defined semantic for categories, in the way they relate content.

We forced that behaviour by adding the `track` selector, but without being a category in the hugo sense.

Categories are part of the internal hugo plumbing that could have helped us.

**Comment by VasBu** [comment]
@fzipi , thanks a lot for your response.
I'm going over all GitHub issues trying to cover all things mentioned the past period and close down the issues that are not relevant anymore or add additional attributes/labels to those which are, and move them in a project respectively. 

It's looks like this one has to be closed. Thank you very much for the response.
