### ISSUE TITLE
Find better solution for adding borders images

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#205]
I tried 

![image](https://user-images.githubusercontent.com/656739/38472458-6f66182e-3b78-11e8-8beb-f2bf77bed719.png)

which was causing this

![image](https://user-images.githubusercontent.com/656739/38472457-6ab7135a-3b78-11e8-86f0-80e3aba9b909.png)

So for now I'm going to use a shortcode called `img-border`

![image](https://user-images.githubusercontent.com/656739/38472495-e1b635b2-3b78-11e8-889c-5f3e88a76f60.png)

which can be used like this: 
![image](https://user-images.githubusercontent.com/656739/38472509-e8b86010-3b78-11e8-8961-f89f072fb336.png)

**Comment by fzipi** [comment]
@DinisCruz Is this one solved then?
