### ISSUE TITLE
Create canonical url and redirect other

### ISSUE THREAD

**Issue by fionarichmond** [OpenSecuritySummit/oss2018#231]
It looks like there are two urls
https://open-security-summit.org/
https://opensec-summit.org/

I would recommend putting in a 301 redirect from https://opensec-summit.org/ to https://open-security-summit.org/

This should help with google

**Comment by fzipi** [comment]
This shoud be done in Cloudfront.

**Comment by fzipi** [comment]
Ok, I made that redirection. What should I do with the other domains?
![screenshot from 2018-04-28 12-08-53](https://user-images.githubusercontent.com/3012076/39397908-f984b8d0-4adc-11e8-80ad-addbe660f91d.png)

**Comment by fzipi** [comment]
This was made for that particular domain. If we need another domain redirected, open a new issue in the future.
