### ISSUE TITLE
Add early bird and standard price to tickets page

### ISSUE THREAD

**Issue by fionarichmond** [OpenSecuritySummit/oss2018#238]
It might be good to be really clear about the early bird offer, so people don't get confused/disappointed when the price changes
e.g on the tickets page, have
"SUMMIT + ACCOMMODATION
£1,250*GBP Early bird rate
(Standard price £xxxx.xx* after 31 May 2018)
* plus fee and VAT
5 days x 24h participant
Access to all working sessions
Breakfast, lunch and refreshments during breaks Dinner and drinks Accommodation in Villa (4 nights) End of summit party"
I don't have the standard price details to include here; other ways are to strikethrough the standard price to show the early bird price and/or put a flash across the corner

**Comment by fzipi** [comment]
@devseccon ?

**Comment by DinisCruz** [comment]
I agree and this info needs to be very visible on the on the pricing page, which is not at the moment

![image](https://user-images.githubusercontent.com/656739/39301849-89d428bc-4948-11e8-9a9e-46286aaa149e.png)

**Comment by DinisCruz** [comment]
related to #274

**Comment by VasBu** [comment]
@DinisCruz , would you please provide answers to the following questions:

1. What is the standard price if early bird rate is £1,250GBP ?
2. There are three packages on the price page. Are all those prices for all three pages for early bird? If yes, then what are the standard prices for other two pages?

**Comment by almeidam** [comment]
added temp early to home page

https://github.com/OpenSecuritySummit/oss2018/pull/356

**Comment by VasBu** [comment]
@almeidam , maybe it will be good if we add one sentence that early bird prices are valid until 11.May. What do you think?

**Comment by VasBu** [comment]
It's obsolete already. I'm closing this one.
