### ISSUE TITLE
Write a headline and summary for homepage that sums up the summit

### ISSUE THREAD

**Issue by JemmaDSmith** [OpenSecuritySummit/oss2018#241]

**Comment by fionarichmond** [comment]
I sent this to @Lisa-devseccon 
The place where AppSec comes to make change happen. 

Join us for this unique event where you will connect, learn and collaborate. Not just your usual conference with plenaries and a single stream, the Open Security Summit takes you away from your everyday work and immerses you in Working Sessions to collaborate and come up with deliverables, and User Sessions to upskill and get hand-on experience, as well as plenty of opportunity to network with some of the most-skilled professionals in this field.

Set in 365 acres of natural woodland at Woburn Forest Center Parcs, the Summit gives you the opportunity to focus all your energy on the here-and-now, hang out with some cool people and leave knowing you are at the top of your game.

**Comment by DinisCruz** [comment]
this is done 
![image](https://user-images.githubusercontent.com/656739/39300256-0172156a-4943-11e8-81d3-02d56986da90.png)
