### ISSUE TITLE
Write descriptions for tracks https://open-security-summit.org/tracks/

### ISSUE THREAD

**Issue by JemmaDSmith** [OpenSecuritySummit/oss2018#243]

**Comment by fionarichmond** [comment]
Suggested descriptions:
GDPR 
From GDPR Appropriate Security Controls to Real world GDPR practices, this is where the real GDPR security experts will be

DevSecOps
Sessions focusing on the DevSecOps tools and techniques to embed security as part of CI/CD pipelines

Mobile Security
Join this track dedicated to completing the OWASP Mobile Security Testing Guide

OWASP Devslop
Take part in Working Sessions and User Sessions dedicate to OWASP’s newest project, a collection of DevOps-driven applications, specifically designed to showcase security catastrophes and vulnerabilities

OWASP SAMM
Register for this track to join a group working together in a 5-day sprint on SAMMv2

Security Pipelines
Working Sessions include Using activity-oriented metrics for Security and Securing the CI Pipeline

Threat Model
With Working Sessions such as Attack chains as TM technique and 
Threat Model cheat sheets

**Comment by fzipi** [comment]
Descriptions were added to the corresponding tracks..
