### ISSUE TITLE
OSS urgent website improvements

### ISSUE THREAD

**Issue by Lisa-devseccon** [OpenSecuritySummit/oss2018#244]
Homepage / Front page:

@fzipi 
- [x] nav bar items: use oswald font
- [x] reduce padding so that header slider is less high: 60px ->20px
- [x] carousel text make left align
- [x] carousel: use the text and button text from previously supplied pdf
- [x] buttons to have green background and white font
- [x] headline and text to sit underneath the carousel (tbp by me)
- [x] items under carousel: make also headlines links
- [x] to change top nav to right aligned (not urgent)
- [x] combine nav items: SESSIONS -> 1. tracks , 2. working sessions, 3. user sessions
- [x] combine nav items: ABOUT -> 1. About the summit , 2. Venue, 3. FAQ
- [x] tickets to be first nav item
- [x] replace carousel images with smaller images

@lisa-devseccon 
- [x] to send smaller images for carousel
- [x] to resend text to for carousel slides to Felipe

@fionarichmond  
- [x] to write a headline and intro paragraph that can sit under the header carousel slider

@frontexpert 
- [x] please revert the background colour of the sponsor section back to white

Tracks page:

@fzipi
- [x] add page Title in header banner
- [x] change buttons under each track to say 'view sessions'

@frontexpert 
- [x]  to design header banner for sub pages (to be used on all pages apart from homepage) – something simple that works for all pages
- [x] improve design of the tracks list to make this look more interesting
- [x] implement new track design on page

@fionarichmond  
- [x] Write improved one sentence description for each track

working sessions page:

@frontexpert  
- [x] take image from 'about the summit' carousel slide and pull out parts of it to create two new images: one for working sessions page, one for user sessions page
- [x] implement graphic on page

@fzipi:
- [x] include image in to the right of the intro text
- [x] please make the list of the working sessions a table (and display the border colours in light grey), include a third column that shows the track of each session

User sessions page:

@frontexpert 
- [x] take image from 'about the summit' carousel slide and pull out parts of it to create two new images: one for working sessions page, one for user sessions page
- [x] implement graphic on page

@fzipi: 
- [x] include image in to the right of the intro text
- [x] please make the list of the working sessions a table (and display the border colours in light grey), include a third column that shows the track of each session

@fionarichmond  
- [x] to write intro text that explains what user sessions are

sponsor page
@fzipi
- [x] set sizes for sponsor logos: platinum 1/3 column width, gold 1/4 column width, silver 1/5 column width
- [x] change owasp logo to offical owasp logo https://www.owasp.org/images/thumb/f/fe/Owasp_logo.jpg/300px-Owasp_logo.jpg
- [x] put logos in white boxes with green banners (like last year's)

About page

@fzipi:
- [x]  move image to the right side
- [x]  move that first line of text so it sits with the rest of the paragraph 
- [x] reduce the space between the cube bullets and the text by 50%

@frontexpert 
- [x] to design a nicer layout for the why attend part - perhaps with icons
- [x] implement new layout/ design on page

venue page

@fzipi 
- [x] reduce the space between text and 'view venue button'
- [x] increase the space after the button (between button and 'getting there' headline)
- [x] increase space between map and text

OTHER

@frontexpert 
- [x]  please create social media images that use the graphics from the website, + font styles + text
- [x] one social media image for each of the four carousel sliders
- [x] pass on final graphics to @fionarichmond

**Comment by lisa** [comment]
Hi, I think you mean another Lisa. :)

**Comment by Fiona** [comment]
You've also @'d the wrong Fiona. Whoops!

**Comment by fzipi** [comment]
Did my first pass in 4a4c861.

**Comment by fzipi** [comment]
@fionarichmond We need those texts updated ASAP.

**Comment by fionarichmond** [comment]
Suggested text in response to:  
- to write a headline and intro paragraph that can sit under the header carousel slider
The place where AppSec comes to make change happen. Join us for this unique event where you will connect, learn and collaborate.

**Comment by fionarichmond** [comment]
Suggested texts in response to:  Write improved one sentence description for each track
GDPR 
From GDPR Appropriate Security Controls to Real world GDPR practices, this is where the real GDPR security experts will be
DevSecOps
Sessions focusing on the DevSecOps tools and techniques to embed security as part of CI/CD pipelines
Mobile Security
Join this track dedicated to completing the OWASP Mobile Security Testing Guide
OWASP Devslop
Take part in Working Sessions and User Sessions dedicate to OWASP’s newest project, a collection of DevOps-driven applications, specifically designed to showcase security catastrophes and vulnerabilities
OWASP SAMM
Register for this track to join a group working together in a 5-day sprint on SAMMv2
Security Pipelines
Working Sessions include Using activity-oriented metrics for Security and Securing the CI Pipeline
Threat Model
With Working Sessions such as Attack chains as TM technique and 
Threat Model cheat sheets

**Comment by fionarichmond** [comment]
Suggested text in response to: to write intro text that explains what user sessions are

In addition to Working Sessions this year we are also introducing the concept of User Sessions, which will be very hands-on practically-driven sessions, so you come away with the skills and tools to make immediate changes in your workplace

**Comment by Jonathon** [comment]
Hi I think you mean another Jonathon : )

**Comment by fzipi** [comment]
@Lisa-devseccon 
this one "carousel: use the text and button text from previously supplied pdf" was changed by Jonathon with his new design. Is it needed now?

**Comment by fzipi** [comment]
@Lisa-devseccon Is this too little space?
![screenshot from 2018-04-20 08-45-02](https://user-images.githubusercontent.com/3012076/39049267-3771271c-4477-11e8-88ea-a287abdc00d0.png)

**Comment by fzipi** [comment]
Spacing done.

**Comment by fzipi** [comment]
Changed text in the carousel.

**Comment by Lisa-devseccon** [comment]
@fzipi can you please add this under the carousel banner on the front page (above the section with  icons, on white background):
<h2>The place where AppSec comes to make change happen.</h2>
<p>Join us for this unique event where you will connect, learn and collaborate. Not just your usual conference with plenaries and a single stream, the Open Security Summit takes you away from your everyday work and immerses you in Working Sessions to collaborate and come up with deliverables, and User Sessions to upskill and get hand-on experience, as well as plenty of opportunity to network with some of the most-skilled professionals in this field.<p/>
<p>Set in 365 acres of natural woodland at Woburn Forest Center Parcs, the Summit gives you the opportunity to focus all your energy on the here-and-now, hang out with some cool people and leave knowing you are at the top of your game.</p>

**Comment by Lisa-devseccon** [comment]
@fzipi the header carousel banner is still quite high. Is there more padding/ margin that can be removed inside, above and below the text and graphics?

**Comment by Lisa-devseccon** [comment]
@fzipi could you please add the following text to the intro text on the uder sessions page:

In addition to Working Sessions this year we are also introducing the concept of User Sessions, which will be very learning-based hands-on practically-driven sessions, so you leave with the knowledge, skills and tools you need to make immediate changes in your workplace.

We wanted to introduce User Sessions to this year’s event, as we believe that only by keeping your learning up to date and taking opportunities to try these new skills out for yourself in a safe environment, where it’s ok to fail - and fail fast - will you really be able to go back and implement the new knowledge you have acquired.

The Summit now includes these User Sessions, from working through Chaos Experiments to getting to grips with GDPR Patterns, from understanding how to use OWASP SAMM to using Pixi, we want to cover all the bases.

See also the planned [Working Sessions](https://open-security-summit.org/working-sessions/)

**Comment by fzipi** [comment]
@Lisa-devseccon This is how centered shows:
![screenshot from 2018-04-27 09-42-41](https://user-images.githubusercontent.com/3012076/39363098-70f8113e-49ff-11e8-98ca-c0811e290a25.png)

Is that ok?

**Comment by Lisa-devseccon** [comment]
@fzipi regarding the centered text, i meant the new text on the front page

**Comment by fzipi** [comment]
@Lisa-devseccon Sorry, it was not clear. Seemed awkward anyway :)
Centered text in 1bcc78b.

**Comment by VasBu** [comment]
@Lisa-devseccon , I just looked over the checklist and spotted the last two items that are still open in this issues and those are related to illustrations/images that have to be beside the intro text that you already provided.
Would you tell me please does somebody already work on those images? 
if we already have them, would you please share those images here so we can close two of three open items in under this issue?

**Comment by fzipi** [comment]
@VasBu  Well, I talked a little bit with @Lisa-devseccon a while ago.  I was thinking that the better the sponsorship, the bigger logo you get. Maybe I'm wrong.

I everybody thinks that logos should be the same size, please, write it clear here.

The green part is already included: it's the funds provide by each sponsor. But no one has put that text with the corresponding values.

It's called `funds` in the sponsors data files, located in `data/sponsors/**`. If someone has the funds, please fill them.

**Comment by VasBu** [comment]
Ehej, @fzipi , great info. Thank you.
In that case we don't need to make it the same size as it is for the previous summit.
Let me try to find the information about the funds and if I can get that information I hope you will be able to updated it?

**Comment by VasBu** [comment]
Dear @frontexpert would you please provide solution related to the following two items from the checklist under this issue.

- include image in to the right of the intro text (working sessions) [link](https://open-security-summit.org/working-sessions/)
- include image in to the right of the intro text (user sessions) [link](https://open-security-summit.org/user-sessions/)

We need illustrations that will be besides the intro text. Would you please provide two illustrations?

**Comment by VasBu** [comment]
@Lisa-devseccon , thank you very much for the information and sorry for confusion to you and @frontexpert  as well. It's hard for me to follow discussion on several Slack channels especially about the same topics and subjects. 

I'm trying to increase the usage of GitHub Issues and Project thus we communicate all concrete requirements here as well as to keep the assignee attribute relevant so everyone who is interested can find information about the required activities and requirements here.

Thank you once more @Lisa-devseccon . Would you please just share contact info from Sarah Cruz? (not able to find her on Slack and Github as well)

**Comment by VasBu** [comment]
@fzipi , please check #162. I move that one in the list of P1 priorities because looks like solution for one of the items in the checklist under this Issue.

![image](https://user-images.githubusercontent.com/15072044/39691753-db57cb5a-51de-11e8-8850-44807dcc2143.png)

**Comment by VasBu** [comment]
@sarahallencruz , Would you please share information with us, do we have separate illustration for the "User Sessions" page that has to be place beside the text or we can use the same one as you provided under #162 for the "working sessions"?

**Comment by sarahallencruz** [comment]
Hi @VasBu, I don't have a new illustration for user sessions but I think this one would work well.
<img width="1465" alt="for user sessions" src="https://user-images.githubusercontent.com/38696765/39694087-f6b0e3f6-51dd-11e8-8af2-de40114ab646.png">

**Comment by VasBu** [comment]
@sarahallencruz Excellent! Thank you Sarah for the prompt response. (pining @fzipi to see that information B-))

**Comment by VasBu** [comment]
I created three separate issues related to the items that has been left oped for the large check list.
