### ISSUE TITLE
Working & User Session Status Table View

### ISSUE THREAD

**Issue by almeidam** [OpenSecuritySummit/oss2018#246]
Create Working Session Status Table. 

Session Name, Track, Draft (check), Organizer Name, Content Ready (check), Event Date, Room, Participants(link to part. list or dropdown list), Featured

![image 3](https://user-images.githubusercontent.com/4119205/38928078-9f7fde58-42ff-11e8-9511-3939296754c8.png)
![image 2](https://user-images.githubusercontent.com/4119205/38928079-9fb8b37c-42ff-11e8-9ffe-ba4f798a1929.png)

**Comment by fzipi** [comment]
@almeidam This is for `admin`, right?

**Comment by almeidam** [comment]
@fzipi  Yes it is.

**Comment by fzipi** [comment]
@almeidam I've made my initial version on https://open-security-summit.org/admin/sessions-status/. It is incomplete.
Will do a second version later today.

**Comment by almeidam** [comment]
Felipe that looks great! Nice birds view.

**Comment by fzipi** [comment]
Second version online.

**Comment by almeidam** [comment]
Looks great @fzipi a good amount of info.

**Comment by DinisCruz** [comment]
this is really cool :)
![image](https://user-images.githubusercontent.com/656739/39310956-a497bda6-4963-11e8-8414-4e1c7125a0d5.png)
