### ISSUE TITLE
Create tracks admin table

### ISSUE THREAD

**Issue by fzipi** [OpenSecuritySummit/oss2018#250]
Use this pdf as example: [[OSS2018][Tracks]Sessions.pdf](https://github.com/OpenSecuritySummit/oss2018/files/1927841/OSS2018.Tracks.Sessions.pdf)

**Comment by fzipi** [comment]
Here is the table: https://open-security-summit.org/admin/tracks/

**Comment by almeidam** [comment]
tracks added
