### ISSUE TITLE
Should we archive the https://github.com/OWASP/open-security-summit repo?

### ISSUE THREAD

**Issue by fzipi** [OpenSecuritySummit/oss2018#26]

**Comment by fzipi** [comment]
That repo was created before this one. Archiving means to make it read-only, for now. But you need to archive it for that.

**Comment by DinisCruz** [comment]
Just deleted the repo. here is the zip of it (for archive)

[open-security-summit-master.zip](https://github.com/OpenSecuritySummit/oss2018/files/1950695/open-security-summit-master.zip)
