### ISSUE TITLE
SEO for 'Owasp Summit 2018'

### ISSUE THREAD

**Issue by sarahallencruz** [OpenSecuritySummit/oss2018#263]
We need to point people searching for Owasp Summit 2018 to the Open Security Summit site. Create a holding page that explains the change of name and links to the OSS site.
<img width="833" alt="screen shot 2018-04-24 at 15 47 04" src="https://user-images.githubusercontent.com/38696765/39195777-6a47f968-47d8-11e8-8c35-76b1c0077983.png">

**Comment by fzipi** [comment]
The thing here is that it is *not* the OWASP Summit. I think this is an expected search for that term. Do we need to do something at the owaspsummit.org site? If yes, where is the text that we should put there?

**Comment by VasBu** [comment]
@fzipi , @sarahallencruz , I'll close this one. We already have information about the new summit and where the interested party can found more information.

![image](https://user-images.githubusercontent.com/15072044/40704768-629bcfc8-63e9-11e8-8c7b-e67192660378.png)
