### ISSUE TITLE
Add email subscription option to site

### ISSUE THREAD

**Issue by JemmaD** [OpenSecuritySummit/oss2018#264]

**Comment by fzipi** [comment]
So, this should be a dynamic form? Or just a list in github?

**Comment by VasBu** [comment]
@fzipi, usually is a form through which user can provide email address and that will be stored in some repository which should not be visible for the public. 
As far as I know there is a mailchimp repository with emails from the participants that attended to the past summits. Maybe we have to be consistent and add email addresses to mailchimp?
I don't think that we have to expose them. @JemmaDSmith , @DinisCruz ?

**Questions: ** @JemmaDSmith , @DinisCruz : what was the idea of collecting email addresses from the interested parties? Are we sending some newsletters to them? How do we plan to use them? What will be the suitable format in which we have to collect those emails?

**Comment by fzipi** [comment]
I would like to know more about this. Implementing dynamic stuff, on a static site, needs some thought.

**Comment by VasBu** [comment]
@fzipi I think this might be obsolete. We already have emails from participants on their profile pages. 
I'm sending a question to @devseccon  and @Lisa-devseccon to confirm that we can skip this one.
