### ISSUE TITLE
Improve design of pricing page 

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#274]
- move day ticket to top (so that we don't scare the participants) 
 - add info about the early bird ticket

and the boxes don't look good

![image](https://user-images.githubusercontent.com/656739/39302124-7ac4643a-4949-11e8-8684-56e87c518996.png)

**Comment by fzipi** [comment]
@frontexpert Do you have that nice design (number 2) you posted in Slack?

If you add the corresponding css, I will gladly add the hugo part.

**Comment by frontexpert** [comment]
@fzipi Please check provided html/css of pricingpage.

**Comment by fzipi** [comment]
Uploaded and finished already.
