### ISSUE TITLE
 Create first pass at schedule page 

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#280]
Which maps the main tracks locations and the keynotes

We need a design for this

**Comment by DinisCruz** [comment]
Hi @VasBu I'm going to have a go at this

**Comment by VasBu** [comment]
Great to read that. B-)

**Comment by Lisa-devseccon** [comment]
@DinisCruz can you please add a view of schedule per day, which shows sessions from all tracks (incl. times/ locations) that are planned for each day? That way it will be easier for participants that are interested in several tracks to plan their day.

**Comment by VasBu** [comment]
@DinisCruz , would you please confirm that this one is finished so I can close the issue?
Thank you.
