### ISSUE TITLE
Improve home page

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#281]
Assuming that is the only page a visitor will see, we need to show:

 - featured Tracks 
 - featured Sessions 
 - featured Participants 
 - keynotes
 - pictures from last Summit

**Comment by VasBu** [comment]
The following link includes some nice photos from the previous summits but do not include photos from OWASP 2017, at least as far as I can see.

Where can be found hi res photos from the last summit?

**Comment by VasBu** [comment]
Questions that might help us to determine the additional content for the homepage.
@DinisCruz , would you please answer to the following questions:

1. What are the featured tracks for this summit? 
To be honest Open Security is not my strongest topic but my basic knowledge and my modest knowledge of the situation is that GDPR has an update which It becomes enforceable on 25 May 2018. So the topics related to "**GDPR**" could be really attractive. Also "**Mobile Security**"? (Usage of mobile devices is something that has constant increase) Also "**DevSecOps**". This concept especially in a software development context is really attractive to the people who are part of it and I believe the list of participants in those processes is large. 

2. What are the features sessions?
Again, maybe GPDR, "Mobile Security" and "DevSecOps" have to be pool from which the featured sessions will be selected.
Just an idea: another approach it might be we spotted the most attractive organizers (the champions in the security community) and featured sessions to be mainly selected by that criteria?

3. What is the criteria for featured participants? Are you referring to organizers?

**Comment by VasBu** [comment]
Just brief information to those who might be concerned that I do plan to make a mock-up for the homepage for the parts that has to be added, aligning the mock-up with a hint from @DinisCruz that we have to look at the homepage like into landing and leaving page and this page to include the most important content and messages that have to be send to a visitor, but in a compact format.

**Comment by VasBu** [comment]
@almeidam , I spotted that you made some changes in the sliding banner of the home page which are in a line with this issue. 

I was thinking to an update which will extend the logical parts of the website to few more that will correspond with the topics mentioned of the description of this issue. 
Something similar to the following:
![image](https://user-images.githubusercontent.com/15072044/39706138-b93ec35c-5210-11e8-8281-0ff9e48317f9.png)

What do you think?

I'm sure some of the team mates (@frontexpert or @sarahallencruz) can develop great layout.

**Comment by Lisa-devseccon** [comment]
lisa to create mockup for featured tracks/ keynote/ participates section

**Comment by Lisa-devseccon** [comment]
@fzipi can you please implement the below design for the featured section on the front page? 
the headline "featured" should be in the same style as the "sponsors" headline further below. Also, in the interest of quick implementation, I have used the same style for the three boxes as used for the ticket boxes on the tickets page (including the hover style). Let me know if you can easily copy this style from the tickets page or if you need more input from me regarding style details.
[oss-website-featured-v01.pdf](https://github.com/OpenSecuritySummit/oss2018/files/2021148/oss-website-featured-v01.pdf)

**Comment by fzipi** [comment]
@Lisa-devseccon So I added the featured stuff to the main home page. The thing is that.. there is no featured content for that stuff available. 
![screenshot from 2018-05-21 23-09-26](https://user-images.githubusercontent.com/3012076/40338547-0cac46f4-5d4c-11e8-94dd-ba8ab9e366f4.png)
So I will upload the changes, and set the config to not show that part until we have more featured content.

**Comment by Lisa-devseccon** [comment]
@fzipi ok, cool. Is there a way to create a 'featured' category for certain keynotes / track/ participants on the backend? And can the green buttons be adjusted so that they are always at the bottom of the box? 
featured tracks should be: DevSecOps, Threat Modeling and Chaos Engineering

**Comment by fzipi** [comment]
@Lisa-devseccon For the `keynotes`, I think that will suffice. For the tracks, and participants, just add `featured: yes`.
I'm adding `featured: yes` to those tracks. But participants featured? That's way out for my decision making algorith :)

**Comment by Lisa-devseccon** [comment]
;) Francois told me to feature the following participants:
Adam shostack
Franziska Buehler
Tony Richards

Is there a way to make this a randomly generated list? So that every time someone loads the page this show three random entries?

Thanks!

**Comment by fzipi** [comment]
So, it's going live.
![screenshot from 2018-05-24 22-55-25](https://user-images.githubusercontent.com/3012076/40522123-9b144ddc-5fa5-11e8-9528-690987f821f4.png)

**Comment by fzipi** [comment]
It's not that easy to generate random people.....

**Comment by Lisa-devseccon** [comment]
@fzipi ok, lets put this on hold for now. thanks for implementing the above.
