### ISSUE TITLE
Create presentation about the Summit (for others to present)

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#283]
With latest info on tracks and sessions
... who is going to be there
...why you should go

uploaded to slideshare and made available as pdf on site 

here is one I've created recently (but we need to do better) : https://www.slideshare.net/DinisCruz/open-security-summit-april-2018

![image](https://user-images.githubusercontent.com/656739/39303410-e5963e9c-494d-11e8-88e1-919c2204ee39.png)

see here for a number we created last year : https://www.slideshare.net/search/slideshow?searchfrom=header&q=owasp+summit&ud=any&ft=all&lang=**&sort=

![image](https://user-images.githubusercontent.com/656739/39303358-c049b402-494d-11e8-84c8-ee09870168c5.png)

**Comment by VasBu** [comment]
@DinisCruz , The summit already has website (at least it will have to be finished in the next 10 days I guess) with relevant information what it is all about, what are the tracks and at least most of the sessions, who are the organizers, where it will happen and why to attend.

Would you please be specific what is the aim of this presentation and is it only required a PDF format from it?
We already have an issue (#285) which is similar to this one, at least it looks similar to me. the only difference is PDF format or maybe some PPT format?

**Comment by DinisCruz** [comment]
Well it would be good to have a presentation similar to this one  https://www.slideshare.net/DinisCruz/owasp-summit-2017-24-days-to-go

maybe saying something like 10 days to go.... here are all the great things happening at the Summit

**Comment by DinisCruz** [comment]
I'll take this one

**Comment by Lisa-devseccon** [comment]
![slide](https://user-images.githubusercontent.com/27144792/40054341-ca45aa28-5844-11e8-9c83-f63d3332870a.png)
