### ISSUE TITLE
Create page that allows the easy explanation of the what the summit is

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#285]
At the moment if I want to explain what is the summit, I have to use this presentation since it allows me to tell a story

https://www.slideshare.net/DinisCruz/open-security-summit-april-2018

Please see below the story I usually tell (can you see how we need a page to tell this)

--------

### Here is what the summit is all about (all these people coming together and collaborating)

![image](https://user-images.githubusercontent.com/656739/39304216-e154c7ce-4950-11e8-8e8e-51e869b02c37.png)

### here is the collaboration in action

![image](https://user-images.githubusercontent.com/656739/39304271-112f9398-4951-11e8-9789-76cddf3b56f6.png)

 - **top left**: working sessions on security champions and DevSecOps (during the day)
 - **top right**: working session on threat modeling (during the evening)
 - **bottom left**: collaboration at the evening on the villas
 - **bottom middle**: Owasp mobile team working hard (on the villa) on the release of the book
 - **bottom right**: book released by mobile team

### here is the next summit (where and when)

![image](https://user-images.githubusercontent.com/656739/39305443-081eaf1a-4955-11e8-95dc-9f940e1141b0.png)

### some text about what the summit it

![image](https://user-images.githubusercontent.com/656739/39305901-9473d12e-4956-11e8-96dd-a6e1c2146e64.png)

### what are the tracks we have

![image](https://user-images.githubusercontent.com/656739/39306026-e6870e18-4956-11e8-87f6-e8217b2fcc1d.png)

### what are the Working sessions we have 

![image](https://user-images.githubusercontent.com/656739/39306043-eff15fda-4956-11e8-8557-7a64ad657122.png)

and 

![image](https://user-images.githubusercontent.com/656739/39306146-374a7722-4957-11e8-9da8-b9ef681a4b1a.png)

### cost and venue

![image](https://user-images.githubusercontent.com/656739/39306164-44e415c8-4957-11e8-9932-6621ea90c3bc.png)

**Comment by VasBu** [comment]
@DinisCruz , The website already has "About" page. What do you think about:

- updating the content with a bit more juicy intro text (like telling a story) even I personally don't think that the text is bad.
- providing some photos or maybe videos from the past Summit (people like to see photos and videos. People are getting lazy nowadays they want to watch, they don't want to read a lot B-)

If you think it is good idea, It will be good the introduction text to be revised by somebody who has good writing skills? As far as I understood @fionarichmond has some outstanding writing skills or am I wrong?
Where we can find some hi res photos from the past summit? Maybe some videos?

What do you think?

**Comment by VasBu** [comment]
The following Issue is similar to this one, #51.

**Comment by Lisa-devseccon** [comment]
Easy to understand/ why I should go text: lisa to add text below 'why attend' that people can also download as pdf. Jemma to provide text. Lisa to create mockup

**Comment by JemmaDSmith** [comment]
By attending the event, I will develop valuable skills, build key networks, and enhance the profile of our organisation globally.

This is a unique event is organised with the support of the Open Web Application Security Project (OWASP), a worldwide not-for-profit charitable organization focused on improving the security of software. During this event, I will:
- Improve my expertise by meeting leading figures from OWASP, security, development, government agencies and vendor companies.
- Bring back action plans by collaborating in working sessions tackling some of the hardest security problems we are facing in 2018
- Learn new skills at sessions at hands-on practically-driven sessions, enabling me to return with the knowledge,, skills and tools I need to make impactful changes

**Comment by Lisa-devseccon** [comment]
@fzipi can you please replace the text on the 'About' 'The Summit' page with the following (but leave the the 'why attend' part as is):

The Open Security Summit 2018 is focused on the collaboration between Developers and Application Security and organised with the support of the Open Web Application Security Project (OWASP): a worldwide not-for-profit charitable organization focused on improving the security of software. Using the same model as the previous OWASP Summits, it will be a 5-day high-energy experience, during which attendees get the chance to work and collaborate intensively. This is not a conference with uni-directional presentations. Every thoroughly prepared working session is geared towards a specific Application Security challenge and will be focused on actionable outcomes.

If you care about Application Security and want to collaborate with the key players in this industry, this is the event to be at. By attending you will develop valuable skills, build key networks, and enhance the profile of our organisation globally. During the Summit you will:

- Improve your expertise by meeting leading figures from OWASP, security, development, government agencies and vendor companies
- Bring back action plans by collaborating in working sessions tackling some of the hardest security problems we are facing in 2018
- Learn new skills at hands-on practically-driven sessions, enabling you to return with the knowledge, skills and tools needed to make impactful changes

**Comment by VasBu** [comment]
Updated.
