### ISSUE TITLE
Make the option for remote participation more visible and understood

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#293]
At the moment it looks like this which doesn't really make it visible

![image](https://user-images.githubusercontent.com/656739/39308021-4f7c34de-495c-11e8-91c9-f7fa1cb014bd.png)

related to #292

**Comment by VasBu** [comment]
@fzipi , Maybe it will be much better we use some icon/illustration which will indicate to remote participants. 
@fzipi , what do you think about the following?
- replace the text "For remote participants see here" with "remote participants"
- make the text a bit more bigger that a visitor can spot it easier. (increase the size of the font)
- find some free icon which will make association to remote person and put that one above the current text 
- centralize the text and the icon above the list of "current physical list of Summit attendees".
- make decent space between the new icon and the text "For reference here are the Participants from the last Summit: https://owaspsummit.org/website/participants.html"
![image](https://user-images.githubusercontent.com/15072044/39530000-478319d4-4e28-11e8-847d-c1c3bda3a72d.png)
- make the text and the icon a link to the current page for remote participants.

What do you think!? Or, maybe you have some other more creative solution which make this link/information much more visible?

**Comment by fzipi** [comment]
I didn't find a suitable icon for now.
![screenshot from 2018-05-03 01-01-32](https://user-images.githubusercontent.com/3012076/39559568-976ea130-4e6d-11e8-9a42-ac32be7aaa55.png)

**Comment by VasBu** [comment]
This one looks good. I think we can publish that one and when we find an appropriate icon we can make one more update. (I'll drop a message to the designer(s) if they can provide something appropriate.

**Comment by fzipi** [comment]
This is published already.
