### ISSUE TITLE
Add quotes from last Summit (to all pages and areas)

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#298]
Maybe as a small popup, or layover or at the bottom of the pages

We should also map out the great blog posts written about the last Summit

**Comment by DinisCruz** [comment]
here are some designs from Sarah

![image](https://user-images.githubusercontent.com/656739/39311231-47f15200-4964-11e8-9069-075179c8bf5f.png)

**Comment by VasBu** [comment]
I'm sharing one more comment that express an experience from a visitor of the summit 2017.
This comment was posted on Slack **OWASP** workspace, **@chapter-ua** channel.

![image](https://user-images.githubusercontent.com/15072044/39910989-f529321c-54f9-11e8-8a90-c3bd445c5e74.png)
