### ISSUE TITLE
Add video about Owasp mobile project publishing the book to Leanpub (last Summit)

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#301]
Note: I have this video

This is a great moment from the last Summit

**Comment by VasBu** [comment]
I think that this one have to be part of the page for the summit 2017 which will be integral part of the website for the summit 2018.

Please confirm that this one is the video that you refer to.
https://photos.google.com/share/AF1QipP70pBJFWzy7q3fFwM9sxbFMPmzpvFyre8g9pMeH4spIeXaeYTT-YaWiah6j51hwg/photo/AF1QipN7Dw5JVQdAUoExBEQ5oEL-7dJQfpXPEIdAIRkU?key=Z1FpVlM1ZVgyOEpNclRUV2hvZnR4U2RYQUVhS2RB

related to the request of creating a page for the summit 2017 #42
