### ISSUE TITLE
Home link is redundant (on top menu)

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#310]
not only it is available from the top right logo (common for most websites)

and the home page doesn't add any value

![image](https://user-images.githubusercontent.com/656739/39312836-5dc5fdc0-4968-11e8-9da9-275eef01c571.png)

**Comment by fzipi** [comment]
Well, I think @Lisa-devseccon asked for it? What do we do?

**Comment by Lisa-devseccon** [comment]
yes, I asked for it. Most pages have a home button I was struggling to find my way back to the front page sometimes. Since we've condensed the navigation I thought it would be could to add it.

**Comment by VasBu** [comment]
Please check all pages. Looks like every page has separate implementation for the main menu.
For instance, if you go to participants page, you will be able to see the "home" item, still.

![image](https://user-images.githubusercontent.com/15072044/39529329-af896f62-4e26-11e8-8677-15e147ad6897.png)

**Comment by VasBu** [comment]
Now is ok.
