### ISSUE TITLE
Add booked day to the session page 

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#314]
for example 
![image](https://user-images.githubusercontent.com/656739/39314014-35a1eb1c-496b-11e8-8ebc-144fe25df81b.png)

which is on 

- https://open-security-summit.org/working-sessions/juice-shop/brainstorming/
- https://open-security-summit.org/working-sessions/security-buttons/

**Comment by VasBu** [comment]
@DinisCruz , This one looks like implemented. I'll set this one to close.
