### ISSUE TITLE
Add gdpr patterns content from pre-summit working session to summit session 

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#318]
from here https://open-security-summit.org/working-sessions/pre-summit/gdpr-patterns/ 

to https://open-security-summit.org/tracks/gdpr/working-sessions/creating-standard-for-gdpr-patterns/

**Comment by almeidam** [comment]
done, waiting for review

**Comment by fzipi** [comment]
Merged.
