### ISSUE TITLE
For the participants sponsored , add a link + logo to their participant page

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#319]
the label used is 'sponsored-by'
for example 

![image](https://user-images.githubusercontent.com/656739/39319506-225abb7a-4979-11e8-98e8-375ea2d5e022.png)

**Comment by fzipi** [comment]
@DinisCruz I have this implemented. The thing is that for example, there are many participants sponsored by `CertDev`. So I created #471 because of this.

Until we don't add all sponsors, I think this would break things.

**Comment by VasBu** [comment]
I reminded @devseccon yesterday about CerDev, still no materials from them.

**Comment by fzipi** [comment]
We have the logo, and it was added as sponsor. Will do the last stuff for adding this.
