### ISSUE TITLE
Order tickets by cheapest to most expensive on ticket page

### ISSUE THREAD

**Issue by JemmaDSmith** [OpenSecuritySummit/oss2018#325]

**Comment by fzipi** [comment]
@JemmaDSmith Well, make up your mind :) @fionarichmond said otherwise in #230.

**Comment by fionarichmond** [comment]
Lol - my experience of A/B split testing says that whatever you put on the left hand side drives the highest conversion. This is with a commercial hat on, which may not be the main driver for this website, in which case the rationale is different. Highest first is my suggestion, but not necessarily the preferred choice for the organisers. 
Sorry not to give a definitive decision.
