### ISSUE TITLE
Early banner to be added to carousel

### ISSUE THREAD

**Issue by JemmaDSmith** [OpenSecuritySummit/oss2018#329]

**Comment by fzipi** [comment]
Where is the text/image for this banner?

@JemmaDSmith , @almeidam BTW, adding items to the carousel should be simple to extend. Just upload your image to `static/img/carousel` directory, and them copy any yaml file from `data/carousel` with your new name, and edit it to match whatever you want. For example, if you want to have a banner with the early, copy for example `data/carousel/about.yaml` to `data/carousel/early.yaml` and change weigth (basically the order) and text, and you are set!

**Comment by almeidam** [comment]
added

**Comment by almeidam** [comment]
added to home page
