### ISSUE TITLE
Add sponsors' funds values on sponsors page

### ISSUE THREAD

**Issue by VasBu** [OpenSecuritySummit/oss2018#374]
- Please put that text with the corresponding values for sponsors' funds
- **TIP HOW TO ADD SPONSORS' FUNDS VALUES:** It's called funds in the sponsors data files, located in data/sponsors/**. If someone has the funds, please fill them.

The funds' values will be displayed under the sponsors' logos
![The funds' values will be displayed under the sponsors' logos](https://user-images.githubusercontent.com/15072044/39697255-938c1076-51f0-11e8-90b7-d22a0b175dd2.png)

The representation will be similar to the page from the previous summit
![The representation will be similar to the page from the previous summit](https://user-images.githubusercontent.com/15072044/39697295-bfe5e6d8-51f0-11e8-8100-eb4e0021858e.png)

**Comment by devseccon** [comment]
spoke to some sponsors who are not comfortable to have these values displayed. therefore let's close this issue
