### ISSUE TITLE
Update "working sessions" page

### ISSUE THREAD

**Issue by VasBu** [OpenSecuritySummit/oss2018#376]
- Please use the posted graphical design (SS1) to update the web page for "Working Sessions" (https://open-security-summit.org/working-sessions/)
- Please add the following illustration (SS2) beside the intro text for the page "Working Sessions" page (https://open-security-summit.org/working-sessions/)
- Please keep the current page header (Do not implement the header from the SS1)

Working Sessions page layout (SS1)
![Working Sessions page layout](https://user-images.githubusercontent.com/15072044/39698937-4230f758-51f7-11e8-8d08-138f694e1ec7.png)

Working Sessions page illustration (SS2)
![Working Sessions page illustration](https://user-images.githubusercontent.com/15072044/39699150-2f0ea7dc-51f8-11e8-8194-e47171a675fe.png)

**Comment by fzipi** [comment]
Fixed in that commit.
