### ISSUE TITLE
Insert illustration on the tickets page

### ISSUE THREAD

**Issue by VasBu** [OpenSecuritySummit/oss2018#380]
- Please insert the following illustration into the tickets page;
<img width="928" alt="ticketspackages" src="https://user-images.githubusercontent.com/15072044/39756386-b1feefea-52c9-11e8-8c0d-fba250dab610.png">

- the illustration has to be inserted bellow the tickets packages.

![image](https://user-images.githubusercontent.com/15072044/39756420-d92c6cbe-52c9-11e8-83d3-0701d16de2f2.png)

**Comment by fzipi** [comment]
@VasBu Inserted already. Please check size/location.

**Comment by VasBu** [comment]
@fzipi Sounds good to me at this point. We have some other required activities that has high priority as well. Moving this one to closed we can back to it if we have some time.
The illustration is good and at least by my opinion it gives additional explanation what a participant can get from each package.
