### ISSUE TITLE
Update tracks' view to correspond with the information on sessions list pages

### ISSUE THREAD

**Issue by VasBu** [OpenSecuritySummit/oss2018#405]
Update page that includes information about the tracks and the sessions for the tracks (https://open-security-summit.org/tracks/) thus the updated information will correspond with information on pages for users and working sessions list. (https://open-security-summit.org/working-sessions/ | https://open-security-summit.org/user-sessions/)

![image](https://user-images.githubusercontent.com/15072044/39859648-cae7ca46-543a-11e8-8152-63d8c92da271.png)

**Comment by almeidam** [comment]
by assign working sessions to tracks this will be resolved.  this issue should be merged with #404
