### ISSUE TITLE
Disable/Remove early bird prices from eventbrite page after 11.May (Friday)

### ISSUE THREAD

**Issue by VasBu** [OpenSecuritySummit/oss2018#407]
Assumption: End date for early bird prices for the tickets is 11.May (Friday)

- Disable/Remove options with early bird prices for tickets allowed on Eventbrite page. (https://www.eventbrite.co.uk/tickets-external?eid=42524734626&ref=etckt)
![image](https://user-images.githubusercontent.com/15072044/39872821-7289d018-5469-11e8-985a-03b330a1f91b.png)

**Comment by devseccon** [comment]
done
