### ISSUE TITLE
Update the illustration with ticket prices

### ISSUE THREAD

**Issue by VasBu** [OpenSecuritySummit/oss2018#416]
- [ ] Starting from 12.May early bird prices are not valid anymore. Please update the following illustration with the standard prices for the tickets.
<img width="928" alt="39698096-4bf71ab2-51eb-11e8-9dfd-20f4dcdceb86" src="https://user-images.githubusercontent.com/15072044/39957702-a1ec3c26-55f7-11e8-8927-fce4436b3b5c.png">
Standard prices are the following: 

![image](https://user-images.githubusercontent.com/15072044/39957729-f0063a2e-55f7-11e8-9a27-ef96fc27767e.png)

- [x] Update new version of the illustration to the ticket page (https://open-security-summit.org/tickets/)

**Comment by VasBu** [comment]
@almeidam , that illustration as far as I'm aware has not been updated.
@sarahallencruz ?

**Comment by almeidam** [comment]
https://open-security-summit.org/tickets/ this page has been updated you can close it
