### ISSUE TITLE
'The last summit' page to be created

### ISSUE THREAD

**Issue by fzipi** [OpenSecuritySummit/oss2018#42]

**Comment by fzipi** [comment]
Using 
https://www.slideshare.net/owaspsummit/owasp-summit-debrief-v10-jun-2017?qid=8d0fa85b-5fb4-4f96-bb54-5d727dc44b83&v=&b=&from_search=1 from slide 28

**Comment by m4sterbunny** [comment]
@fzipi do you mean the images? If so I assume we need to go to source for decent quality?
![image](https://user-images.githubusercontent.com/20266893/37029582-aceb201a-2140-11e8-9a32-0b36d4b590b7.png)

**Comment by JemmaDSmith** [comment]
You should be able to lift from https://twitter.com/OWASPSummit for speed if that helps?

**Comment by m4sterbunny** [comment]
gonna lift content from here https://github.com/OpenSecuritySummit/oss2018/edit/master/content/oss2017/blog/2017-05-08-Best-InfoSec-Problem-Solving-Event.md
and images from twitter

**Comment by fzipi** [comment]
@m4sterbunny Was this page commited? Do we need to do something more?

**Comment by VasBu** [comment]
Dear @m4sterbunny ,

We are mobilizing ourselves to finalize all the important things about the summit's website. 
This issue represents one of the requirements which are marked as important for the website. 

Would you please share information with the team about this page? 
Did you manage to finalize?
Are you available in the next days? Are you able to finish it?
Do you need any help, assistance so you will be able to finish the page about the previous summit? 
How can I help you?

Best

**Comment by VasBu** [comment]
@fzipi , Would you please take this one?

**Comment by VasBu** [comment]
Photos from the summit 2017 can be found to the following URLS:

**Photo Album:** https://photos.app.goo.gl/emmfMMNW4FMTNg7l1
**pics in Summit debrief:** https://www.slideshare.net/owaspsummit/owasp-summit-debrief-v10-jun-2017

**Comment by VasBu** [comment]
Please find the selected 26 photos and re-touched (edited) in the following location: \static\img\summit2017

**Comment by VasBu** [comment]
@fzipi , sounds like during the life-cycle of this issue several times has been reference to presentations (https://www.slideshare.net/owaspsummit?utm_campaign=profiletracking&utm_medium=sssite&utm_source=ssslideview) from the past summit which has to be refined into a textual description for this page. 
As far as I'm aware, no concrete content. I tried to contact @fionarichmond if he would be able to write some content but it looks like Finoa is not available this period.

But, I was thinking... we already have some nice photos. Maybe we can create a page under "About" which will say Previous Summit and behind that link we load a new page with the photo gallery from the past summit. (photos repository: \static\img\summit2017) 
In the mean while I can see if I can provide some appropriate textual content which we can use to update the same page.

What do you think!? Can you please create that page and make photo gallery inside?

**Comment by VasBu** [comment]
OK. Let's test my Hugo skills. B-)

**Comment by VasBu** [comment]
Most of the things has been implemented. This relatively large page includes the following chapters:

- [ ] **The Legacy** - textual description required
- [x] **Photo Gallery** 
- [x] **Results**
- [x] **Quotes from community**
- [ ] Review textual description on the page. (validate semantic and English language)

@DinisCruz , @Lisa-devseccon , @devseccon

**Comment by Lisa-devseccon** [comment]
@VasBu let me know how I can help with the above.

**Comment by VasBu** [comment]
@Lisa-devseccon , thank you for the prompt response. 

- Please make review of the layout and if you have some suggestions from your perspective please just let me know so I can make edit.
- I believe the page will looks much better with some specific header banner.
- If you have any idea for additional section that can be make the story about the previous summit even better, I would be glad to add that content to the page.  

![about summit 2017](https://user-images.githubusercontent.com/15072044/40541714-37c726f0-601d-11e8-90ba-f7e714f3f1a6.png)

**Comment by VasBu** [comment]
Useful presentation in a context of telling a story about the 2017 summit and "The Legacy" heading.
https://www.slideshare.net/DinisCruz/owasp-summit-2017
