### ISSUE TITLE
Track link from session page redirects to the old page for tracks

### ISSUE THREAD

**Issue by VasBu** [OpenSecuritySummit/oss2018#423]
**NOTE:** Not sure that this one is a real bug.

1.  Go to page details for a sessions (for instance https://open-security-summit.org/tracks/devsecops/working-sessions/appsec-soc-monitoring-visualisation/)
2. Click on the track name 
![image](https://user-images.githubusercontent.com/15072044/39984052-2c063728-575a-11e8-9228-1fb6e28b0fd7.png)

3. The website will redirect to old page for tracks

**Comment by fzipi** [comment]
Fixed in 8226aa79ab648a5fceae613881ef4c5d7d7e2828.
