### ISSUE TITLE
The link back to the Track is not working

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#433]
For example when coming from an working session

![image](https://user-images.githubusercontent.com/656739/40010597-226f7ba0-579d-11e8-9483-2da205b0b9ad.png)

clicking on the link to the Track (in this case https://open-security-summit.org/tracks/#owasp-devslop) shows:

![image](https://user-images.githubusercontent.com/656739/40010629-3a52d28a-579d-11e8-95c2-50a064e0167c.png)

which is the content of the home page for the tracks

**Comment by VasBu** [comment]
@fzipi please check this one.

**Comment by fzipi** [comment]
This happens because of the javascript code that changes tabs is not accepting parameters, I think.

**Comment by VasBu** [comment]
I guess we can't do too much about this one? Maybe we should close this one and live with the problem?

**Comment by fzipi** [comment]
I am trying to debug this. Don't close it for now.
