### ISSUE TITLE
Internal files on Admin folder

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#434]
Is there a particular reason why these files are in this folder

![image](https://user-images.githubusercontent.com/656739/40011166-e0bcd840-579e-11e8-8601-d84b64e5ffec.png)

which means that they will be copied to the `public` folder

![image](https://user-images.githubusercontent.com/656739/40011191-f34233b6-579e-11e8-9810-8d0bb1359331.png)

**Comment by VasBu** [comment]
@DinisCruz ,
Actually I was not aware what admin folder is and I think I read some response that tracking of organizing sessions has to be done in that folder, so I started creating some spreadsheets in that folder. 

But I really got the context after I dive into the code for the website and after I discover Admin page on the summit 2017 (https://owaspsummit.org/website/summit-organization.html).

So, I'm removing those files from there.
