### ISSUE TITLE
Are we showing in one place the Working Sessions not in a track

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#436]
Am I missing something?

If we are not, we are missing a trick by not giving the visitors an good way to see and register for these sessions

**Comment by VasBu** [comment]
@DinisCruz , I'm not sure that I understand this one.

as far as I was able to understand the structure of the website about the sessions and tracks...

- tracks and sessions are defined inside content\tracks
- the mentioned folder is used to generate tracks view (https://open-security-summit.org/tracks/)
- in the dame time by using the files in content\tracks sessions list (https://open-security-summit.org/working-sessions/ and https://open-security-summit.org/user-sessions/)
- the previously mentioned sessions list views, are generated from content\working-sessions and content\user-sessions folders as well but in this case they can't be displayed under the tracks in the view for tracks (https://open-security-summit.org/tracks/)

**Summary**
We display sessions in two views: 
- under the tracks (https://open-security-summit.org/tracks/) and 
- in a flat lists (https://open-security-summit.org/working-sessions/ | https://open-security-summit.org/user-sessions/)

**Comment by VasBu** [comment]
I guess this one can be closed.
