### ISSUE TITLE
Font in sessions list in Candidates page is too big

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#437]
the links looks like this

![image](https://user-images.githubusercontent.com/656739/40041448-e209bf16-5815-11e8-94dc-a092bf47be8c.png)

which is too big when compared with the other links

![image](https://user-images.githubusercontent.com/656739/40041475-f86383aa-5815-11e8-8fb7-dda9ce1bd0c1.png)

**Comment by VasBu** [comment]
I think that there was a explicit requirements from @devseccon , the font size to be increased, but I agree that it should be a bit smaller than it is.
@fzipi ?

**Comment by devseccon** [comment]
The requirement was for the font to be identical everywhere on the site and especially on the participant schedule as it’s currently too big

**Comment by VasBu** [comment]
@devseccon . OK. Clear.

**Comment by VasBu** [comment]
@devseccon , @DinisCruz 
Done. the font size is set to 14px, the same size as it is list of sessions under the tracks page.
I just changed the font size in CSS  `.particpant` (custom.css, line 1218)

Font size might be changed depend on the screen that mobile device has, but will don't try to make any changes at this point for mobile version.
