### ISSUE TITLE
mockup footer: twitter, slack, github  icons, contact details

### ISSUE THREAD

**Issue by Lisa-devseccon** [OpenSecuritySummit/oss2018#446]

**Comment by Lisa-devseccon** [comment]
@fzipi could you please implement the attached footer design on all OSS website pages? 
[OSS-2018-footer-v01.pdf](https://github.com/OpenSecuritySummit/oss2018/files/2012322/OSS-2018-footer-v01.pdf)
here are the social media icons
[social icons.zip](https://github.com/OpenSecuritySummit/oss2018/files/2012324/social.icons.zip)

**Comment by fzipi** [comment]
@Lisa-devseccon Please check the uploaded footer. One thing that I didn't know was the official twitter link...

**Comment by devseccon** [comment]
It’s @opensecsummit

**Comment by Lisa-devseccon** [comment]
@fzipi thanks, the footer looks good on the desktop version of the website. On my mobile the headline font is looking wrong – is there a way to fix this? Also, if we could decrease the font size on mobile it would look better.
![image1](https://user-images.githubusercontent.com/27144792/40236228-212ad90c-5aad-11e8-97d2-66f78341313e.png)
