### ISSUE TITLE
create printed summit guide

### ISSUE THREAD

**Issue by Lisa-devseccon** [OpenSecuritySummit/oss2018#449]

**Comment by Lisa-devseccon** [comment]
I suggest we do something similar to last year: a folded leaflet that has a map and sponsor logos on one side and general information on the other side
[OWASP Summit conference guide v05 - print ready.pdf](https://github.com/OpenSecuritySummit/oss2018/files/2022413/OWASP.Summit.conference.guide.v05.-.print.ready.pdf)
We could use flyeralarm to print: https://www.flyeralarm.com/uk/shop/option/index/id/88/quantity/11506450/shipping/4/customizedId#options
250 copies for 86 GBP, next day delivery

@JemmaDSmith @DinisCruz @SebaDele @devseccon what's your opinion?

**Comment by JemmaDSmith** [comment]
[SWOPTR02218052114260.pdf](https://github.com/OpenSecuritySummit/oss2018/files/2022569/SWOPTR02218052114260.pdf)
Villa locations

**Comment by Lisa-devseccon** [comment]
[OSS-summit-guide-2018-v05c(print-ready).pdf](https://github.com/OpenSecuritySummit/oss2018/files/2057535/OSS-summit-guide-2018-v05c.print-ready.pdf)
