### ISSUE TITLE
bug in media breakpoints

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#453]
note how in the example below the table goes out of the screen once I expand the window by a couple pixels

![image](https://user-images.githubusercontent.com/656739/40072149-ca78ac22-586a-11e8-84a5-7d63c0cf1426.png)

and 
![image](https://user-images.githubusercontent.com/656739/40072167-d47a8358-586a-11e8-87a3-eff4581d7737.png)

**Comment by VasBu** [comment]
The solution in \static\css\custom.css.
![image](https://user-images.githubusercontent.com/15072044/40249761-43ab0a02-5ad4-11e8-8635-244c32cd9b1a.png)
