### ISSUE TITLE
The clues icons should go to pages that explain it

### ISSUE THREAD

**Issue by DinisCruz** [OpenSecuritySummit/oss2018#454]
for example on 
![image](https://user-images.githubusercontent.com/656739/40095312-381740b0-58c3-11e8-9d92-7d770631573a.png)

 - [x] the 'Needs organiser' goes to https://open-security-summit.org/faq/organisers-duties/ which is great
- [x] the 'Draft' doesn't go anywhere (should go to a page asking for the data to be added and linking to a couple examples of what it looks like) _@fionarichmond , would would please write few sentances_ 
- [x] the 'Working Sessions' and 'User Sessions' go to https://open-security-summit.org/working-sessions/ and https://open-security-summit.org/user-sessions/ which is ok, but either we add an explanation to those pages on what is the difference, or we point these links to a page that explain that...
- [x] (including Keynotes) _@fionarichmond , can you provide description about keynotes?_

**Comment by VasBu** [comment]
Related to the following Issue #286
