### ISSUE TITLE
CertDev new sponsor?

### ISSUE THREAD

**Issue by fzipi** [OpenSecuritySummit/oss2018#471]
If we have a new sponsor, where can we find the logo, website and data?

**Comment by VasBu** [comment]
The latest information from @devseccon (Francois) is the CertDev are still making their website and he still waits materials (logo). I'll add/attache the materials when we will have it.

**Comment by VasBu** [comment]
![image](https://user-images.githubusercontent.com/15072044/40653509-b030be0a-633b-11e8-8a2e-6b9ae9806c26.png)
