### ISSUE TITLE
Create specific header banner for the team's page

### ISSUE THREAD

**Issue by VasBu** [OpenSecuritySummit/oss2018#479]
- [x] design dedicated banner for a team's page (https://open-security-summit.org/teams/devseccon/)
- [ ] Implement newly created banner into the website

**Comment by Lisa-devseccon** [comment]
![teams](https://user-images.githubusercontent.com/27144792/40235563-f86a07ec-5aaa-11e8-9c07-bf38ad9950dd.jpg)
@VasBu here's the banner for the team page

**Comment by Lisa-devseccon** [comment]
@fzipi could you please implement the above banner and make it look like the header banners on the other pages?

**Comment by VasBu** [comment]
Thank you, @Lisa-devseccon
