### ISSUE TITLE
Create faq content for "Draft" clues icon

### ISSUE THREAD

**Issue by VasBu** [OpenSecuritySummit/oss2018#480]
- Create short textual description about "Draft" clues icon which will be contained by a faq page.
- "Draft" clues icon represents a draft status of a session that has to be finsihed

**Comment by VasBu** [comment]
It is related to #454.

**Comment by Barbarapre** [comment]
text : Content has not been finalised yet. Some of the required content is already available but further details will be added. The session description is not fully ready.  Further updates is expected.
