### ISSUE TITLE
Empty rows in tables with working and user sessions

### ISSUE THREAD

**Issue by VasBu** [OpenSecuritySummit/oss2018#502]
- In working and user sessions pages (https://open-security-summit.org/working-sessions/ | https://open-security-summit.org/user-sessions/) there are few empty rows at the begging of the list which has to be removed.

![image](https://user-images.githubusercontent.com/15072044/40250940-274c37e2-5ad8-11e8-9af0-8bf651db5f19.png)

**Comment by fzipi** [comment]
I think that those are the templates (_template.md) for each type of sessions. Will try to hid them.
