### ISSUE TITLE
Community Custom Schedules

### ISSUE THREAD

**Issue by VasBu** [OpenSecuritySummit/oss2018#503]
# Overview
**The main idea** behind the **custom schedules** is to provide separate calendar with schedules for the community team.

# Specific Requirements
- Community team members has to has possibility to create and update their own (custom) schedules.
- The preview of the custom schedules has to be displayed under the schedule page (https://open-security-summit.org/schedule/)
- Sessions that would be defined for the community custom schedule will have to be distinct from users and working sessions
- The community custom schedules has to be easily update by community team members.

**Comment by DinisCruz** [comment]
With the latest features added to the site, this is now done :)
