### ISSUE TITLE
Can we have a default banner, with look & feel updated?

### ISSUE THREAD

**Issue by fzipi** [OpenSecuritySummit/oss2018#505]
We have updated a lot of banners from the site, but there are some pages that still have the original grey banner, and I think we should substitute it.

Can we implement one default banner, so each page that doesn't have a specific one gets that one? One sort of summit-ish that can go everywhere :)

**Comment by Lisa-devseccon** [comment]
@fzipi good idea, please use this one:
![default-header-banner](https://user-images.githubusercontent.com/27144792/40288059-c234a6d8-5cb1-11e8-8507-203ca2bcef3d.png)

**Comment by fzipi** [comment]
This was implemented.
