### ISSUE TITLE
Create content like https://www.devseccon.com/about-devseccon/ for OSS

### ISSUE THREAD

**Issue by JemmaDSmith** [OpenSecuritySummit/oss2018#51]

**Comment by m4sterbunny** [comment]
@JemmaDSmith do you want to give me thoughts: https://github.com/OpenSecuritySummit/oss2018/blob/master/content/drafts/who-we-are.md

**Comment by VasBu** [comment]
This one is related to update of about page (https://open-security-summit.org/about/)

It looks like that proposal (https://github.com/OpenSecuritySummit/oss2018/blob/master/content/drafts/who-we-are.md) by m4sterbunny is obsolete, @JemmaDSmith , would you please confirm that!?
