### ISSUE TITLE
Picture on participant page is not showing

### ISSUE THREAD

**Issue by swierckx** [OpenSecuritySummit/oss2018#513]
On my particpant page my picture is not showing, the URL seems to be correct (it loads the picture).

Page: https://github.com/OpenSecuritySummit/oss2018/edit/master/content/participant/toreon/steven-wierckx.md

**Comment by swierckx** [comment]
I refreshed the webpages but I still do not see my picture, neither in the list of participants nor in the personal page. Frederic Tollens seems to have the same problem.

I attached screenshots of both pages.

greets

Steven

**Comment by VasBu** [comment]
@swierckx , thank you for the explanation. We try to identify what is the issue.

**Comment by fzipi** [comment]
I can see both images. @swierckx Could you try using a private window in (chrome|firefox)? Just to take all cache out.

**Comment by VasBu** [comment]
Fixed
