### ISSUE TITLE
opensecsummit.org address for all logistics team members

### ISSUE THREAD

**Issue by VasBu** [OpenSecuritySummit/oss2018#562]
**Create email addresses** with **opensecsummit.org** domain for all persons which has to receive emails from the visitors and give a feedback/help

**Comment by JemmaDSmith** [comment]
Majorie Mohammad will need email address

**Comment by VasBu** [comment]
@JemmaDSmith , Do we know who else except Majorie M. will have to have opensecsummit.org email to be support team member during the summit?
