### ISSUE TITLE
Update footer with short and explicit information to the help center

### ISSUE THREAD

**Issue by VasBu** [OpenSecuritySummit/oss2018#566]
**Update the website** so the visitors can easily find contact for help (FAQ page "I need help" to be updated, update short info how to report a problem in some visible place on the site - Manuel had good idea that place to be the footer)

**Comment by almeidam** [comment]
Also add the slack help link  OSS Helpdesk - https://os-summit.slack.com/messages/CAVJH8QJV

**Comment by VasBu** [comment]
New link has been added.
![image](https://user-images.githubusercontent.com/15072044/40781820-a032d30a-64dd-11e8-9430-c362ba43e53b.png)
