### ISSUE TITLE
Create OSS PowerPoint template

### ISSUE THREAD

**Issue by JemmaDSmith** [OpenSecuritySummit/oss2018#57]

**Comment by Lisa-devseccon** [comment]
here is the ppt template:
[OSS 2018 presentation tempalte v01.pptx](https://github.com/OpenSecuritySummit/oss2018/files/2012362/OSS.2018.presentation.tempalte.v01.pptx)

**Comment by Lisa-devseccon** [comment]
@JemmaDSmith please see ppt template above
