### ISSUE TITLE
Early bird available up to 30 April, then increase from May

### ISSUE THREAD

**Issue by JemmaDSmith** [OpenSecuritySummit/oss2018#59]

**Comment by JemmaDSmith** [comment]
@devseccon please add closing date to eventbrite

**Comment by fionarichmond** [comment]
@devseccon is this still correct as it's missing from the current site?
If so, I'll add to the flier and/or email campaigns.

**Comment by devseccon** [comment]
This has now been added to the ticket description

**Comment by almeidam** [comment]
Here are the prices for both on eventbride.
https://www.eventbrite.co.uk/tickets-external?eid=42524734626&ref=etckt
