### ISSUE TITLE
end-of summit party organisation (BBQ)

### ISSUE THREAD

**Issue by VasBu** [OpenSecuritySummit/oss2018#597]
- location
- music
- other ideas?

**Comment by TonyDRichards** [comment]
I can bring a trailer speaker (speaker with built in amp, can play anything via RCA/3.5mm jack, so a laptop and spotify account will do).

**Comment by devseccon** [comment]
Go for it Tony.

Francois

**Comment by fzipi** [comment]
Can be closed. Nice party!
