### ISSUE TITLE
Feedback required

### ISSUE THREAD

**Issue by m4sterbunny** [OpenSecuritySummit/oss2018#64]
@SebaDele please can you give me some feedback for the about

**Comment by m4sterbunny** [comment]
1. should rather be called "who are we" ??? or ??? there is already an about

**Comment by SebaDele** [comment]
yes "who are we"

**Comment by m4sterbunny** [comment]
name change done- I also have inline comments, so it helps to look at my work in edit view!

**Comment by JemmaDSmith** [comment]
Have reviewed @m4sterbunny I think we can work on the inline comments later, the key is to get content up and ready to go

**Comment by m4sterbunny** [comment]
does this replace the current about or sit underneath 1 layer

**Comment by fzipi** [comment]
I think we can close this one now.
