### ISSUE TITLE
Platinum sponsors required scrolling on home page 

### ISSUE THREAD

**Issue by VasBu** [OpenSecuritySummit/oss2018#715]
Not all platinum sponsors are visible on the home page.
A visitor will need to scroll to be able to see all platinum sponsors. 

![image](https://user-images.githubusercontent.com/15072044/40713922-7c9fdc1c-6401-11e8-9d61-985b7a20381d.png)

**Comment by fzipi** [comment]
This is because a carousel is used also here. I will change that to a simple list.

**Comment by fzipi** [comment]
Fixed.
