### ISSUE TITLE
Create logos for Teams "Women in Tech" and "Security Champions"

### ISSUE THREAD

**Issue by VasBu** [OpenSecuritySummit/oss2018#748]
- [x] Create logos for the mentioned teams.
- [x] Edit page with teams to add the logos.

![image](https://user-images.githubusercontent.com/15072044/40777064-fe153b5e-64cc-11e8-89a4-73899fddc039.png)

**Comment by Lisa-devseccon** [comment]
![security-champions](https://user-images.githubusercontent.com/27144792/40785403-b5650e5e-64e8-11e8-8853-f7b31fb4d8dc.png)
![women-in-tech](https://user-images.githubusercontent.com/27144792/40785405-b58a5bfa-64e8-11e8-8feb-738df98f7598.png)
@VasBu can you please use these

**Comment by VasBu** [comment]
Thank you @Lisa-devseccon .
Update has been finished and pull request has been created.
