### ISSUE TITLE
Google Meet link for each session

### ISSUE THREAD

**Issue by VasBu** [OpenSecuritySummit/oss2018#767]
- We have to provide link to a Google Meet call for remote participants.
- [x] Every page for a sessions has to include a link that will redirect to a Google Meet call/room. (Create `meet_url:` tag)
- [x] Schedule pages have to include link that will access a Google Meet call respectively.
- [x] Update `meet_url:` tag by adding relevant URL to Google Meeting call/room.

![image](https://user-images.githubusercontent.com/15072044/40797194-9c899944-6507-11e8-8d1b-709583b5d86c.png)

**Comment by fzipi** [comment]
Let's use the `meet_url:` tag for this. We can choose to have generic link, for example for each room, and then if we need some session with a special link, use the tag for that.

Or we can add the tag to each session. For me either way is the same.

I have added the code to my local template, but didn't found yet the meet icon to add.

**Comment by fzipi** [comment]
Added the layouts links.
![screenshot from 2018-06-01 13-08-06](https://user-images.githubusercontent.com/3012076/40851191-f8811fa2-659c-11e8-833d-97d30755746f.png)

**Comment by fzipi** [comment]
Can be closed.
