### ISSUE TITLE
Participating sessions details is showing the outcomes instead of session?

### ISSUE THREAD

**Issue by fzipi** [OpenSecuritySummit/oss2018#784]
This is for my user:

![screenshot from 2018-06-01 08-26-20](https://user-images.githubusercontent.com/3012076/40838703-cd157aec-6575-11e8-90c5-7ac12b580b06.png)

Or title should say otherwise, or we are listing the wrong type.

**Comment by itscooper** [comment]
I'm having this same issue and can't quite work it out...

![2018-06-01 14_20_19-chris cooper](https://user-images.githubusercontent.com/7916070/40843066-b43bb41e-65a7-11e8-81f7-2c7f1a62e965.png)

https://open-security-summit.org/participant/tickets/chris-cooper/

I've just listed the name of each session following a hyphen which seems to be what others have done. Have I missed something?

```
sessions:
- Owasp Testing Guide v5
- Running CTF Games with OWASP Juice Shop
- SAMM2 Kickoff
- OwaspSAMM - Best Practices
- SAMM Introduction
- SAMMv2 working session - Governance
- SAMMv2 working session - Implementation
- SAMMv2 working session - Verification
- SAMMv2 Establish the Document Model
- SAMM benchmarking
- SAMM Project Meeting
```

**Comment by fzipi** [comment]
@itscooper No, yo didn't miss anything. We just need to fix that :)

**Comment by fzipi** [comment]
This happened because we duplicated the title for the outcomes..
