### ISSUE TITLE
create web page for outcomes

### ISSUE THREAD

**Issue by Lisa-devseccon** [OpenSecuritySummit/oss2018#833]
- [x] page design
- [x] implement design

**Comment by fzipi** [comment]
Added background.

**Comment by fzipi** [comment]
Reviewing the design, all the outcome pages will have a title of "Outcome", am I right? Because right now the title is the session/outcome name.
![screenshot from 2018-06-02 17-29-24](https://user-images.githubusercontent.com/3012076/40880625-dcbf8918-668a-11e8-85d9-08721ca3c071.png)

**Comment by fzipi** [comment]
This is what I have now:
![screenshot from 2018-06-02 22-31-57](https://user-images.githubusercontent.com/3012076/40882323-d5f2bf40-66b4-11e8-9195-370fdda97539.png)

Will try to finish and push this before the long silence until my flight landes.

**Comment by Lisa-devseccon** [comment]
@fzipi I think the headline in the banner should always be 'outcomes'.
The headline (i.e. DPO how to become one) should be session/ outcome name.

Thanks!

**Comment by Lisa-devseccon** [comment]
@fzipi also I have noticed that all links currently have the wrong green. It should be #8DB93F
