### ISSUE TITLE
Update front page design 

### ISSUE THREAD

**Issue by Lisa-devseccon** [OpenSecuritySummit/oss2018#834]
- [x] create updated front page design
- [x] implement updated design

**Comment by Lisa-devseccon** [comment]
Here's the updated design for the front page / home page, @fzipi and @DinisCruz can you please implement?
[oss-website-during-the-summit-v02.pdf](https://github.com/OpenSecuritySummit/oss2018/files/2065205/oss-website-during-the-summit-v02.pdf)
![outcomes](https://user-images.githubusercontent.com/27144792/40879083-c56deb8a-6692-11e8-8b77-33177202c4b7.png)

**Comment by fzipi** [comment]
Finished with all. The outcomes part is going to be filled when the outcomes are marked as featured.
