### ISSUE TITLE
create persona specific question pages

### ISSUE THREAD

**Issue by Lisa-devseccon** [OpenSecuritySummit/oss2018#835]
- [x] create web page design
- [ ] write questions and answers @Ambg05 
- [ ] create pages (x4)

**Comment by Lisa-devseccon** [comment]
here is the design for the persona specific help pages – @fzipi @DinisCruz we need to create 4 pages in this style for:
1. I'm an on-site participant
2. I'm a remote participant
3. I'm a session organiser
4. I'd like to join the summit

the final text for the pages can be found here: ...
[oss-website-during-the-summit-on-site-participant-v01 copy.pdf](https://github.com/OpenSecuritySummit/oss2018/files/2065208/oss-website-during-the-summit-on-site-participant-v01.copy.pdf)

**Comment by fzipi** [comment]
Got the design, working on it.

**Comment by Ambg05** [comment]
All the Q & As & PRs created.
