### ISSUE TITLE
working session ideas

### ISSUE THREAD

**Issue by m4sterbunny** [OpenSecuritySummit/oss2018#89]
Please, can I have some input to slim this down to the most relevant? I have stayed away from OWASP top ten and the like, they can be included.

I kept draft = true for now

**Comment by m4sterbunny** [comment]
https://github.com/OpenSecuritySummit/oss2018/blob/master/content/potentialWorkingSessions/ideas.md

**Comment by m4sterbunny** [comment]
NB small unused list inside <!-- in file

**Comment by JemmaDSmith** [comment]
@m4sterbunny 
<img width="1180" alt="screen shot 2018-03-09 at 16 06 30" src="https://user-images.githubusercontent.com/34240078/37216884-e55f2994-23b3-11e8-9f38-453ac96e7314.png"> please use these as a starting point

**Comment by m4sterbunny** [comment]
I was thinking 5 categories with 3 items. But above breaks down into 6 by 2, then a more... to click through to full list for that category??
"Join us to improve and understand from these great workshops, or add to the suggestions list and start making it real.

## Agile Appsec
- Agile Practices for Security Teams
- Security Guild vs Security Champions
more...

## CISO
- CISO Survey
- Cyber Insurance
more...

## DEVSECOPS
- AppSec SoC Monitoring Visualisation
- Docker Security
more...

## EDUCATION
- AppSec BSc Masters Curriculum Design
- Creating AppSec Talent
more...
## OWASP
- OWASP PROJECTS
- OWASP TESTING GUIDE
more...

## THREAT RESPONSE
- SECURITY PLAYBOOKS
- THREAT MODEL
more...

"

**Comment by fzipi** [comment]
I think the best way of organizing this is to use the `categories: ` and `tags:` in the front matter.

Then we can play with the output to show it in the best way we can.

So, each title should be a category, and when we need to group some of the content we can add tags to it.

**Comment by m4sterbunny** [comment]
Yes! catTags.
The other functionality I need is the 2017 data remain static, whilst the 2018 data is dynamic.

**Comment by JemmaDSmith** [comment]
@devseccon @DinisCruz @SebaDele can you clarify how you want this to work?

**Comment by m4sterbunny** [comment]
Without direction I keep moving in *a* direction... hence here is an evolved 2017 (i.e. those OWASP 2017 just became OSS 2017) 

Should I strip organisers and participants in the way I did here??

https://github.com/OpenSecuritySummit/oss2018/blob/master/content/oss2017/session/Agile-AppSec/Agile-Practices-for-Security-Teams.md

**Comment by JemmaDSmith** [comment]
@fzipi can you recreate the screenshot in this year's site?

**Comment by fzipi** [comment]
@JemmaDSmith I could recreate this screenshot, but this stuff is created from content.. that we don't have yet.
I suppose I could commit some vanilla sessions with the required categories just to populate this one.

**Comment by m4sterbunny** [comment]
@JemmaDSmith still lost in the woods here- can I have 5 mins with you at end of cx meet to see if you can advise?

**Comment by JemmaDSmith** [comment]
Please do


> On 16 Mar 2018, at 13:21, Felipe Zipitría <notifications@github.com> wrote:
> 
> @JemmaDSmith I could recreate this screenshot, but this stuff is created from content.. that we don't have yet.
> I suppose I could commit some vanilla sessions with the required categories just to populate this one.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 




*This message and any attachment are confidential and may be privileged or 
otherwise protected from disclosure.If you are not the intended recipient 
you must not copy this message or attachment or disclose the contents to 
any other person.For more information please contact:  **info@photobox.com 
<info@photobox.com>*

*PhotoBox Group, Unit 7, Metal Box Factory, 30 Great Guildford Street, 
London, SE1 0HS*

*http://group.photobox.com <http://group.photobox.com/>*

**Comment by DinisCruz** [comment]
closing since this structure will now grow organically
