### ISSUE TITLE
DS shows up every day in the ALL schedule

### ISSUE THREAD

**Issue by SebaDele** [OpenSecuritySummit/oss2018#906]
The session "A seat at the table"
shows up every day in the same timeslot on the schedule
https://opensecsummit.org/schedule/all/
it is only scheduled for Monday

**Comment by fzipi** [comment]
Well, finally I found the culprit.
```
  {{ $.self.Scratch.Add (trim . "") (slice $page) }}
```

We are using a temporary variable which is not initialized each time, so we carry the values over.
