### ISSUE TITLE
Remove all mention of OWASP Summit from site unless in reference to last year's summit

### ISSUE THREAD

**Issue by JemmaDSmith** [OpenSecuritySummit/oss2018#91]

**Comment by m4sterbunny** [comment]
https://github.com/OpenSecuritySummit/oss2018/edit/master/content/articles/OutcomesBasedStrategy.md

can someone suggest correct link to Wiki pages please

**Comment by JemmaDSmith** [comment]
Summit schedule for now will be https://open-security-summit.org/tracks/

**Comment by JemmaDSmith** [comment]
GitHub issues link will be https://github.com/OpenSecuritySummit/oss2018/issues
