### ISSUE TITLE
https://github.com/OpenSecuritySummit/oss2018/blob/master/content/drafts/who-we-are.md

### ISSUE THREAD

**Issue by m4sterbunny** [OpenSecuritySummit/oss2018#98]
Jemma- can I switch this off draft now?

I was not sure whether you wanted it to replace the current about - or simply link down from current about??

If it is ok when we do use it I may just put it in the (poorly-named, probably by me) articles folder (which is where the other details about the summit are held)

**Comment by JemmaDSmith** [comment]
@DinisCruz is reviewing content now

**Comment by almeidam** [comment]
reviwed
